services:

  shelly_exporter:
    image: shelly_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure:2
    container_name: shelly_exporter
    ports:
      - "9784:9784"
    volumes:
      - ./shelly-metrics.json:/shelly-metrics.json
    environment:
      LISTEN_ADDRESS: 0.0.0.0:9784