version: '3.4'

services:
  shelly_exporter:
    image: shelly_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: shelly_exporter
    network_mode: "host" 
    ports:
      - 9784:9784
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
