services:
  shelly_exporter:
    image: shelly_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure:2
    container_name: shelly_exporter
    network_mode: "host"
    volumes:
      - ./shelly-metrics.json:/shelly-metrics.json
