{
 "title": "Shelly Temperature",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "Outdoor Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "shelly_ht_temperature{shelly_name=\"S2\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "shelly_ht_temperature{shelly_name=\"S1\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<html>\r\n<script type=\"text/javascript\">\r\n    var renew = setInterval(function(){\r\n    var image = document.getElementById(\"img\");\r\n    var url = \"https://www.wetterdienst.de/maps/radar/Radarfilm_Deutschland.gif\" + \"?\" + Math.random()\r\n    /* console.log(url); */\r\n    image.src = url;\r\n},240000); /* update after 4 minutes - random against cache */\r\n</script>\r\n<head>\r\n</head>\r\n<body>\r\n<img id=\"img\" src=\"https://www.wetterdienst.de/maps/radar/Radarfilm_Deutschland.gif\">\r\n</body>\r\n</html>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 4 },
   "options": {
    "content": "<!doctype html> <html lang=\"de\">\n<head>\n</head>\n<body>\n<a class=\"weatherwidget-io\" href=\"https://forecast7.com/de/51d0513d74/dresden/\" data-label_1=\"DRESDEN\" data-theme=\"original\" data-highcolor=\"#88d976\" >DRESDEN</a>\n<script>\n!function(d,s,id){\n\tvar js,fjs=d.getElementsByTagName(s)[0];\n\tif(!d.getElementById(id)){\n\t  js=d.createElement(s);\n\t  js.id=id;\n\t  js.src='https://weatherwidget.io/js/widget.min.js';\n\t  fjs.parentNode.insertBefore(js,fjs);\n\t  setInterval('__weatherwidget_init()', 1800000) <!-- refresh widget every 30 minutes (1800000 milliseconds): -->\n\t}\n}(document,'script','weatherwidget-io-js');\n</script>\n</body>\n</html>"
   }
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "shelly_ht_temperature", "legendFormat": " {{name}}" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 12 },
   "options": {
    "content": "<html>\r\n<script type=\"text/javascript\">\r\nvar renew = setInterval(function(){\r\n    var image = document.getElementById(\"img2\");\r\n    var url = \"https://www.wetterdienst.de/maps/radar/Radarfilm_Ost.gif\" + \"?\" + Math.random()\r\n    /* console.log(url); */\r\n    image.src = url;\r\n},240000); /* update after 4 minutes - random against cache */\r\n</script>\r\n<head>\r\n</head>\r\n<body>\r\n<img id=\"img2\" src=\"https://www.wetterdienst.de/maps/radar/Radarfilm_Ost.gif\">\r\n</body>\r\n</html>"
   }
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "shelly_ht_humidity", "legendFormat": " {{name}}" }
   ]
  },
  {
   "title": "Sensor Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "shelly_ht_info" }
   ]
  }
 ]
}