{
 "title": "Shelly Rollo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "shelly_25_roller_blind_temperature",
     "legendFormat": "{{shelly_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "shelly_25_roller_blind_voltage", "legendFormat": " {{shelly_name}}" }
   ]
  },
  {
   "title": "Sensor Overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "shelly_25_roller_blind_info" }
   ]
  }
 ]
}